### ISSUE TITLE
I was trying to follow the steps and setup nextjs wordpress headless cms but i am getting error

### ISSUE THREAD

**Issue by akshaynstack** [colbyfayock/colbyfayock.com#44]
The Error I got when i trying to run the app on localhost - 

error - Error: Cannot query field "page" on type "Page". Did you mean "date" or "pageId"?
ApolloError: Cannot query field "page" on type "Page". Did you mean "date" or "pageId"?

**Comment by colbyfayock** [comment]
hi im not providing support for this project, but you can check out the project this is based on over here: https://github.com/colbyfayock/next-wordpress-starter
